### ISSUE TITLE
App dowloaded not openable

### ISSUE THREAD

**Issue by ThibaudM13** [sal0max/muzei-nationalgeographic#16]
Hi!
Such a nice app idea you had!
But sadly, when downloaded, no application is added to my apps and even the open button does not appear in store on your app page (in both store: play store and fdroid).

**Comment by sal0max** [comment]
As stated in the README:
>  This is a plugin for the live wallpaper app Muzei by Roman Nurik. It needs Muzei to be used.
Install Muzei and select NatGeo inside Muzei: https://play.google.com/store/apps/details?id=net.nurik.roman.muzei
