### ISSUE TITLE
once in a while photo stuck

### ISSUE THREAD

**Issue by lucamp** [sal0max/muzei-nationalgeographic#5]
Hi,
I always use the latest photo of the day but once in a while photo stuck without updating. Rebooting do not help. 

The only solution I found is to:

- enable random photo,
- going back and wait until new photo is loaded
- disable random photo and wait until the latest photo is loaded

I noticed that this append when connection problem has occurred, wifi or mobile data either.

How can I debug it?

Meanwhile, could you please add and option to reload the photo on the 3 dot menu at the right of photo's name and data? So it will become:

Share this photo
About this photo
Reload photo
Customize

Thanks again for your app
Luca

**Comment by sal0max** [comment]
Added the feature with a21a6fae9f208d49aa35bc7f9bcedf164f612b12.
